//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagePFE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public int Id { get; set; }
        public Nullable<double> Solde { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<int> IdEmploye { get; set; }
        public Nullable<System.DateTime> DateAjoutSuivante { get; set; }
    
        public virtual Employe Employe { get; set; }
    }
}
